version: 2

models:
    - name: dim_accounts
      description: Customers' account dimension. Contain customer bank account information.
    - name: dim_customers
      description: Customers' dimension. Contain customer demographic information.
    - name: dim_dates
      description: Date dimension.
    - name: dim_merchants
      description: Merchants' dimension. Contain merchants' information.
    - name: dim_transactions
      description: Transaction dimension. Contain customers' transaction type and purpose.
    - name: fct_transactions
      description: Fact transactions. Contain customers' detail transactions and amount.
    # - name: dim_merchants_revenue
    #   description: Information on merchants' total transactions and revenue aggregated by year and month.

metrics:
  - name: amount
    label: Total Spend
    model: ref('fct_transactions')
    description: "Sum of total spend"
    calculation_method: sum
    expression: amount
    timestamp: transaction_date
    time_grains: [month]

    tags:
    - piperider

  - name: customer_key
    label: Total Customers
    model: ref('fct_transactions')
    description: "Count of total customers"
    calculation_method: count_distinct
    expression: customer_key
    timestamp: transaction_date
    time_grains: [month]

    tags:
    - piperider

  - name: merchant_key
    label: Total Merchants
    model: ref('fct_transactions')
    description: "Count of total merchants"
    calculation_method: count
    expression: merchant_key
    timestamp: transaction_date
    time_grains: [month]

    tags:
    - piperider

