base:
  branch: main
  dbt:
    commands:
    - dbt deps
    - dbt build --target prod
  piperider:
    command: |
    piperider init
    piperider run --datasource prod --dbt-state target -o /tmp/piperider/prod-report/
target:
  branch: data-modeling-version01
  dbt:
    commands:
    - dbt deps
    - dbt build --target pr
  piperider:
    command: |
    piperider init
    piperider run --datasource pr --dbt-state target -o /tmp/piperider/pr-report/
